from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['Graph', 'SkipGram', 'WalkGenerator']
class Graph:
    def __init__(self) -> None:
        ...
    def add_edge(self, vertex1: str, vertex2: str, weight: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def add_vertex(self, ID: str, content: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    def are_connected(self, ID1: typing.SupportsInt | typing.SupportsIndex, ID2: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def get_adyacent(self, ID: str) -> list[str]:
        ...
    def get_degrees(self) -> list[int]:
        ...
    def get_nodes(self) -> list[str]:
        ...
    def get_walks(self, num_walks: typing.SupportsInt | typing.SupportsIndex, num_steps: typing.SupportsInt | typing.SupportsIndex, p: typing.SupportsFloat | typing.SupportsIndex, q: typing.SupportsFloat | typing.SupportsIndex) -> list[list[str]]:
        ...
    def get_walks_iter(self, num_walks: typing.SupportsInt | typing.SupportsIndex, num_steps: typing.SupportsInt | typing.SupportsIndex, p: typing.SupportsFloat | typing.SupportsIndex, q: typing.SupportsFloat | typing.SupportsIndex) -> WalkGenerator:
        ...
    def remove_edge(self, vertex1: str, vertex2: str) -> None:
        ...
    def remove_vertex(self, ID: str) -> None:
        ...
class SkipGram:
    def __init__(self, N: typing.SupportsInt | typing.SupportsIndex = 300, subsampling: bool = False) -> None:
        ...
    @typing.overload
    def build_vocab(self, corpus: collections.abc.Sequence[str]) -> None:
        ...
    @typing.overload
    def build_vocab(self, vocab: collections.abc.Sequence[str], frecs: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    def clear(self) -> None:
        ...
    def cosine_similarity(self, word1: str, word2: str) -> float:
        ...
    def get_embedding(self, word: str) -> list[float]:
        ...
    def get_embeddings(self) -> list[list[float]]:
        ...
    def load_model(self, filename: str) -> None:
        ...
    def most_similar(self, word: str, top_k: typing.SupportsInt | typing.SupportsIndex = 5) -> list[tuple[str, float]]:
        ...
    def save_embeddings_bin(self, filename: str) -> None:
        ...
    def save_model(self, filename: str) -> None:
        ...
    def train(self, graph: Graph, epochs: typing.SupportsInt | typing.SupportsIndex, walk_length: typing.SupportsInt | typing.SupportsIndex, p: typing.SupportsFloat | typing.SupportsIndex, q: typing.SupportsFloat | typing.SupportsIndex, K: typing.SupportsInt | typing.SupportsIndex, C: typing.SupportsInt | typing.SupportsIndex, starting_alpha: typing.SupportsFloat | typing.SupportsIndex, verbose: bool, batch_size: typing.SupportsInt | typing.SupportsIndex = 1024, tol: typing.SupportsFloat | typing.SupportsIndex = 9.999999747378752e-05, patience: typing.SupportsInt | typing.SupportsIndex = 10) -> list[float]:
        ...
class WalkGenerator:
    def __init__(self, arg0: ..., std: ..., std: ..., std: ..., std: ..., arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsFloat | typing.SupportsIndex, arg4: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __iter__(self) -> WalkGenerator:
        ...
    def __next__(self) -> list[str]:
        ...
    def next_batch(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> list[str]:
        ...
